language: python

python:
- "3.8"

env:
- DJANGO=2.2

install:
- pip install -r requirements.txt

before_script:
  - python manage.py migrate

script:
  - black --check .
  - flake8 --max-line-length 100 .

deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIAT5SNSXTOQHO4F2XC"
  secret_access_key: "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"
  region: us-east-1
  app: MySite Poll
  env: MySitePoll-dev
  bucket_name: MySite-bucket
  on:
    branch: main 


