[tool.poetry]
name = "mysite"
version = "0.1.0"
description = "vir environ"
authors = ["Your Name <you@example.com>"]
license = "n"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
